export const DJANGOLY_DOCS_URL = "https://github.com/software-trizzey/djazzy-vscode/blob/main/docs/CONVENTION_RULES.md";


export enum RuleCodes {
    // Security-related rules (SEC)
    DEBUG_TRUE = "SEC01",
    HARDCODED_SECRET_KEY = "SEC02",
    EMPTY_ALLOWED_HOSTS = "SEC03",
    WILDCARD_ALLOWED_HOSTS = "SEC04",
    CSRF_COOKIE_SECURE_FALSE = "SEC05",
    SESSION_COOKIE_SECURE_FALSE = "SEC06",
    SECURE_SSL_REDIRECT_FALSE = "SEC07",
    X_FRAME_OPTIONS_NOT_SET = "SEC08",
    X_FRAME_OPTIONS_MISSING_MIDDLEWARE = "SEC09",
    SECURE_HSTS_SECONDS_NOT_SET = "SEC10",
    SECURE_HSTS_INCLUDE_SUBDOMAINS_IGNORED = "SEC11",
    SECURE_HSTS_INCLUDE_SUBDOMAINS_FALSE = "SEC12",
    RAW_SQL_USAGE = "SEC13",
    RAW_SQL_USAGE_WITH_CURSOR = "SEC14",

    // Complexity-related rules (CMP)
    COMPLEX_VIEW = "CMP01",
    FUNCTION_COMPLEXITY = "CMP02",

    // Code Quality-related rules (CDQ)
    NO_EXCEPTION_HANDLER = "CDQ01",
    NAME_TOO_SHORT = "CDQ02",
    FUNCTION_NAME_NO_VERB = "CDQ03",
    FUNCTION_TOO_LONG = "CDQ04",
    CLASS_NAME_CONVENTION = "CDQ05",
    LIST_NAME_CONVENTION = "CDQ06",
    DICTIONARY_VALIDATION = "CDQ07",
    FOR_LOOP_TARGET_VALIDATION = "CDQ08",
    DJANGO_MODEL_FIELD_NAMING = "CDQ09",
    DJANGO_SERIALIZER_FIELD_NAMING = "CDQ10",
    DJANGO_FIELD_CONVENTIONS = "CDQ11",
    COMMENT_VALIDATION = "CDQ12",
    CELERY_TASK_VALIDATION = "CDQ13", // TODO: custom rule. Might move to own category
    REDUNDANT_QUERYSET_METHODS = "CDQ14",

    // Style-related rules (STY)
    BOOLEAN_VARIABLE_PREFIX = "STY01",
    BOOLEAN_VARIABLE_POSITIVE_NAMING = "STY02",
    BOOLEAN_PROPERTY_PREFIX = "STY03",
    BOOLEAN_PROPERTY_POSITIVE_NAMING = "STY04",

    // Configuration-related rules (CFG)
    RESERVED_SYMBOL_HANDLING = "CFG01",

    // Performance-related rules (PER)
    NPLUSONE = "PER01",
}