name: Test Workflow

on:
  push:          # Runs on every push, regardless of branch
  pull_request:  # Runs on every pull request, regardless of branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run compile

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Start xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1280x1024x24 &

      - name: Run client and server tests
        run: |
          chmod +x scripts/e2e.sh
          scripts/e2e.sh
